### ISSUE TITLE
Return public errors instead of inline Errorf

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-plugin-lib-go#30]
E.g. when I get the config of a String https://github.com/intelsdi-x/snap-plugin-lib-go/blob/master/v1/plugin/config.go#L46

I want to be able to test what error I encounter:
```
myString, err := plugin.GetString("mykey")
if err == plugin.NotAString {
	// ...
}
```

**Comment by IRCody** [comment]
@kindermoumoute: This was addressed in #33 wasn't it?
