### ISSUE TITLE
Remove metric.String()

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-plugin-lib-go#34]
This method [`Metric.Namespace.String()`](https://github.com/intelsdi-x/snap-plugin-lib-go/blob/master/v1/plugin/metric.go#L189-L194) should be updated now [Snap PR 1252](https://github.com/intelsdi-x/snap/pull/1252) is merged.

**Comment by bjray** [comment]
We updated the issue name to focus on the removal of this functionality.

Providing a string method implies a guarantee that we are not going to make.  The recommendation will be to remove this method and leave any implementation up to the plugin author.

**Comment by IRCody** [comment]
Closing this as it was addressed by #1301.
