### ISSUE TITLE
Use Snap core.Separator for Namespace.Key()

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-plugin-lib-go#36]
Use core.Separator as delimiter in Namespace.Key().
https://github.com/intelsdi-x/snap-plugin-lib-go/blob/master/v1/plugin/metric.go#L206-L210

Maybe we can have a function `func ParseKey() Namespace` that reverse the process.

EDIT: or remove it. @IRCody

**Comment by IRCody** [comment]
Is it used anywhere? If not I think it's fine to remove it. I'm thinking it might've been invalided by #29.
