### ISSUE TITLE
Make namespace type public

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-plugin-lib-go#40]
As a plugin developer, I want to be able to manage namespaces on the plugin side. 

`plugin.namespace` should be `plugin.Namespace`.

https://github.com/intelsdi-x/snap-plugin-lib-go/blob/master/v1/plugin/metric.go#L32

**Comment by IRCody** [comment]
Can you go into why you want it to be public @kindermoumoute.

**Comment by kindermoumoute** [comment]
Let's say I want to have a function `createMetric` in my collector plugin, with a namespace passed in the argument. Currently I can't do that:
```Go
func createMetric(ns plugin.Namespace) plugin.Metric {
...
```

**Comment by kindermoumoute** [comment]
If you want another use case: https://github.com/intelsdi-x/snap-plugin-collector-psutil/blob/master/psutil/net.go#L65

It's bridling the way people think the code.
