### ISSUE TITLE
Proposal: apply default config values on the plugin side

### ISSUE THREAD

**Issue by kindermoumoute** [intelsdi-x/snap-plugin-lib-go#42]
We still need to send rules, but without the default value. Instead we can apply default value when receiving metrics from gRPC, if required config are empty.

Pros:
- Less data through gRPC.
- Would avoid creating spaghetti code to solve #41 easily.

Cons:
- requires to change all libraries.

**Comment by IRCody** [comment]
@kindermoumoute: When you say change all libraries what do you mean?

**Comment by kindermoumoute** [comment]
Currently we apply default config on the daemon side, so we would have to remove that from the daemon, and do it in all libraries instead. BTW #41 got fixed.

**Comment by IRCody** [comment]
Because of all the changes require on the daemon side, do you think this is more of a proposal for Snap vs the plugin-lib?

**Comment by kindermoumoute** [comment]
Both, but I don't think it's very relevant anymore.

**Comment by IRCody** [comment]
Alright. Going to close it then.
