### ISSUE TITLE
Empty Unit field on CollectMetrics function

### ISSUE THREAD

**Issue by ericho** [intelsdi-x/snap-plugin-lib-go#61]
The `[]plugin.Metric` received on `CollectMetrics` function doesn't have the Unit field as was defined on `GetMetricTypes`.

I tried the following change in the rand collector. This only defines a `string` unit for all the metrics and then will print the content in `CollectMetrics`. 
```
diff --git a/examples/collector/rand/rand.go b/examples/collector/rand/rand.go
index ceaf876..ddd0628 100644
--- a/examples/collector/rand/rand.go
+++ b/examples/collector/rand/rand.go
@@ -70,6 +70,7 @@ The output is the collected metrics as plugin.Metric and an error.
 func (RandCollector) CollectMetrics(mts []plugin.Metric) ([]plugin.Metric, error) {
        metrics := []plugin.Metric{}
        for idx, mt := range mts {
+               fmt.Printf("The Unit for metric %s is %s\n", mt.Namespace, mt.Unit)
                mts[idx].Timestamp = time.Now()
                if val, err := mt.Config.GetBool("testbool"); err == nil && val {
                        continue
@@ -119,6 +120,7 @@ func (RandCollector) GetMetricTypes(cfg plugin.Config) ([]plugin.Metric, error)
                metric := plugin.Metric{
                        Namespace: plugin.NewNamespace("random", val),
                        Version:   1,
+                       Unit:      "string",
                }
                metrics = append(metrics, metric)
        }
```
The output that I get is the following: 

```
DEBU[2017-02-20T21:03:39-06:00] The Unit for metric [{random  } {integer  }] is   _module=plugin-exec io=stdout plugin=test-rand-collector
DEBU[2017-02-20T21:03:39-06:00] The Unit for metric [{random  } {float  }] is   _module=plugin-exec io=stdout plugin=test-rand-collector
DEBU[2017-02-20T21:03:39-06:00] The Unit for metric [{random  } {string  }] is   _module=plugin-exec io=stdout plugin=test-rand-collector
```

Should `string` unit be printed at this point?

Thanks.

**Comment by mkleina** [comment]
@ericho Good question! I think this is just because of current snap workflow. This is not related to snap-plugin-lib-go, because metrics are serialized and sent through RPC the same way both for `GetMetricTypes` and `CollectMetrics`.

Snap executes plugin binary once on plugin load to retrieve `GetMetricTypes` output and then plugin process is killed. Plugin binary is executed again when user creates a task which involves that plugin, and then just `CollectMetrics` is called once per task interval with previously stored metrics as argument, **but only `Namespace` and `Tags` fields are passed**. You decide what data do you need to be collected.

**Comment by ericho** [comment]
Thanks @mkleina for your answer 😄 

So, where the Unit field is used? Is that field used in the publisher plugins? I'm using the file plugin to test and I see that field empty. Is that the same for all publishers?

**Comment by jcooklin** [comment]
> So, where the Unit field is used?

It makes sense for many metrics to advertise a unit.  In snap there is the notion of a metric catalog which is populated when a metric is loaded.  When a task is created the metric is looked up in the catalog and we dispatch a request to the plugin calling CollectMetrics with the metrics from the catalog however we were not passing along the units.  This would require that the plugin author add metrics to both the GetMetricTypes (called on load to update the metric catalog) and in the CollectMetrics.

https://github.com/intelsdi-x/snap/pull/1533 addresses this issue in the framework.  

>Is that field used in the publisher plugins? I'm using the file plugin to test and I see that field empty. Is that the same for all publishers?

Yes it's available and used in the file publisher.   The image below is snapteld running with the commit included in https://github.com/intelsdi-x/snap/pull/1533.  Notice the 'mock units' field. 
![img](https://www.evernote.com/l/AA1-L-Dkg7NCwocBBnXe3gl07ps2tbljTH4B/image.png)

**Comment by ericho** [comment]
Awesome! Thanks @jcooklin I'll use that new version when it's available 😄
