### ISSUE TITLE
[Important] Compatibility issues with grpc

### ISSUE THREAD

**Issue by kristinn** [intelsdi-x/snap-plugin-lib-go#81]
When I started writing my first plugin I ran into lots of issues to just get started, using this library.

It's not compatible with the latest version of `grpc`.

This is the error in question when running `go get` to fetch this library (`snap-plugin-lib-go`).

```
../../intelsdi-x/snap-plugin-lib-go/v1/plugin/rpc/plugin.pb.go:823: undefined: grpc.SupportPackageIsVersion3
```

See https://travis-ci.org/inteleon/snap-plugin-collector-newrelic/builds/223473231 for more information.

I was forced to clone the `grpc` repository manually and then check out a version that works, more specifically version [1.0.3](https://github.com/grpc/grpc-go/releases/tag/v1.0.3) which was released the 18th of October 2016.

**Comment by katarzyna-z** [comment]
Please clear glide cache (`glide cc`) and remove vendor directory. If there's still problem please do not hesitate contact with snap-maintainers on [Slack](https://intelsdi-x.herokuapp.com/).
